blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/sunweaver/nextcloud-high-performance-backend-setup/discussions
    about: Please ask and answer questions here.
